workflows:add support for apply patch

diff --git a/.github/workflows/schedule_update.yml b/.github/workflows/schedule_update.yml
--- a/.github/workflows/schedule_update.yml
+++ b/.github/workflows/schedule_update.yml
@@ -3,9 +3,9 @@ name: Schedule Update
 on:
   schedule:
     - cron: 0 19 * * *
-  push:
-    paths:
-      - '.github/workflows/schedule_update.yml'
+  # push:
+  #   paths:
+  #     - '.github/workflows/schedule_update.yml'
   repository_dispatch:
 
 env:
@@ -47,11 +47,15 @@ jobs:
           # rm -rf `find ./* -maxdepth 0 -type d ! -name "diy"` >/dev/null 2>&1
           rm -rf ./* >/dev/null 2>&1
           bash $GITHUB_WORKSPACE/.github/diy/Update.sh ${{matrix.target}}
-          # TODO:applying patches
-          # find ".github/diy/patches" -type f -name '*.patch' -print0 | sort -z | xargs -I % -t -0 -n 1 sh -c "cat '%'  | patch -d './' -p1 -E --forward --no-backup-if-mismatch" || exit 1
+
+      - name: Modify Code
+        run: |
           bash $GITHUB_WORKSPACE/.github/diy/convert_translation.sh
           bash $GITHUB_WORKSPACE/.github/diy/create_acl_for_luci.sh -a
           bash $GITHUB_WORKSPACE/.github/diy/Modify.sh
+          # 应用补丁
+          cd $GITHUB_WORKSPACE/${{matrix.target}}
+          find "$GITHUB_WORKSPACE/.github/diy/patches" -type f -name '*.patch' -print0 | sort -z | xargs -I % -t -0 -n 1 sh -c "cat '%'  | patch -d './' -p1 -E --forward --no-backup-if-mismatch" || exit 1
 
       - name: Upload
         env:
@@ -103,11 +107,15 @@ jobs:
           # rm -rf `find ./* -maxdepth 0 -type d ! -name "diy"` >/dev/null 2>&1
           rm -rf ./* >/dev/null 2>&1
           bash $GITHUB_WORKSPACE/.github/diy/Update.sh ${{matrix.target}}
-          # TODO:applying patches
-          # find ".github/diy/patches" -type f -name '*.patch' -print0 | sort -z | xargs -I % -t -0 -n 1 sh -c "cat '%'  | patch -d './' -p1 -E --forward --no-backup-if-mismatch" || exit 1
+
+      - name: Modify Code
+        run: |
           bash $GITHUB_WORKSPACE/.github/diy/convert_translation.sh
           bash $GITHUB_WORKSPACE/.github/diy/create_acl_for_luci.sh -a
           bash $GITHUB_WORKSPACE/.github/diy/Modify.sh
+          # 应用补丁
+          cd $GITHUB_WORKSPACE/${{matrix.target}}
+          find "$GITHUB_WORKSPACE/.github/diy/patches" -type f -name '*.patch' -print0 | sort -z | xargs -I % -t -0 -n 1 sh -c "cat '%'  | patch -d './' -p1 -E --forward --no-backup-if-mismatch" || exit 1
 
       - name: Upload
         env:
@@ -118,20 +126,21 @@ jobs:
           git commit -m "schedule update $(TZ='Asia/Shanghai' date +-%m.%d)"
           git push --quiet "https://${{ secrets.ACCESS_TOKEN }}@github.com/hyy-666/openwrt-packages.git" HEAD:${{matrix.target}}
 
-  sync_lean:
-    runs-on: ubuntu-latest
-    name: Sync Lean code
-    strategy:
-      fail-fast: false
-      matrix:
-        target: [master]
-    steps:
-      - uses: TobKed/github-forks-sync-action@master
-        with:
-          github_token: ${{ secrets.ACCESS_TOKEN }}   # 令牌
-          upstream_repository: coolsnowwolf/lede      # 上游仓库
-          target_repository: hyy-666/lede             # 你要推送的仓库
-          upstream_branch: master                     # 默认是拉取上游仓库的master分支
-          target_branch: ${{matrix.target}}           # 默认推送到你的仓库master分支
-          force: false                                # 是否强制推送
-          tags: false                                 # 确定是否使用-tags
+  # TODO:Sync lean code
+  # sync_lean:
+  #   runs-on: ubuntu-latest
+  #   name: Sync Lean code
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       target: [master]
+  #   steps:
+  #     - uses: TobKed/github-forks-sync-action@master
+  #       with:
+  #         github_token: ${{ secrets.ACCESS_TOKEN }}   # 令牌
+  #         upstream_repository: coolsnowwolf/lede      # 上游仓库
+  #         target_repository: hyy-666/lede             # 你要推送的仓库
+  #         upstream_branch: master                     # 默认是拉取上游仓库的master分支
+  #         target_branch: ${{matrix.target}}           # 默认推送到你的仓库master分支
+  #         force: false                                # 是否强制推送
+  #         tags: false                                 # 确定是否使用-tags
